config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :transfers

  get 'contact/contact_info'
  get 'about/about'
  get 'welcome/index'
  get 'show/index'
  get 'show/index1'
  post 'show/index1'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  
  get 'users/new'
  get 'users/:username' => 'users#show'
  get 'users/:username/edit' => 'users#edit'
  post 'users/:username' => 'users#update'
  post 'users/:username/accounts' => 'users#create_bank_account'
  delete 'users/:username/accounts/:account_label' => 'users#delete_bank_account'
  get 'users/:username/accounts/:account_label' => 'transfers#find_account'
  

  resources :show
  resources :dispalies
  resources :users

  root 'welcome#index'

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  # has_many :bank_accounts
  # belongs_to :user
  
  # def from_account
  #   bank_accounts[0]
  # end

  # def to_account_label=
      
  # end


end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  helper_method :bank_accounts_options_for_current_user

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    if !logged_in?
      #flash[]...
      redirect_to '/login'
      return
    end

    @bank_account_options = bank_account_options_for_current_user
    @transfer = Transfer.new
  end


  def do_transaction(from_account, to_account, amount)
  
      from_account.balance -= amount
      to_account.balance += amount
    
    ActiveRecord::Base.transaction do
      from_account.save
      to_account.save
    end
  end

  # POST /transfers
  # POST /transfers.json
  def create

    input_params = transfer_params
    from_account_id = input_params[:from_account_id]
    
    # FIXME: id is actual label!!!
    to_account_label = input_params[:to_account_id]    
    amount = input_params[:amount].to_f

    from_account = BankAccount.find_by id: from_account_id
    if from_account.nil?
      render inline: "can not find sender"
      return
    end

    current_user_bank_account_ids = current_user.bank_accounts.map do |account| 
      account.id
    end 


    puts "from_account_id #{from_account_id}"
    puts "current_user_bank_account_ids #{current_user_bank_account_ids}"

    if !current_user_bank_account_ids.include?(from_account_id.to_i)
      render inline: "You can not operate on other's account"
      return
    end

    puts "to_account_label #{to_account_label}"
    to_account = BankAccount.find_by label: to_account_label

    if to_account.nil?
      render inline: "Can not find receiver"
      return
    end

    to_account_id = to_account.id

    transfer_data = {
      from_account_id: from_account_id,
      to_account_id: to_account_id,
      amount: amount
    }

    @transfer = Transfer.new(transfer_data)
    if @transfer.save
      if from_account.balance < amount
        redirect_to "/transfers/new" 
      else  
        if do_transaction(from_account, to_account, amount)
          puts "transfer success"
          redirect_to "/users/#{current_user.username}"
        else
          render inline: "transfer failed"
          return
        end
      end
      else
        render inline: "transfer failed"
      return
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # transfer 
  #find user
  def find_account

    input_params = find_account_params
    label = user.find_by label: params[:label]

    from_account = input_params[:From_Account]
    to_account = input_params[:To_Account]
    amount = input_params[:Amount]

    print "from_account =========================> #{from_account}"
    print "to_account =========================> #{to_account}"
    print "amount =============================> #{amount}"
  end

  def bank_account_options_for_current_user
    if current_user.nil? || current_user.bank_accounts.nil?
      return []
    end

    current_user.bank_accounts.map do |account|
      [account.label, account.id]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:from_account_id, :to_account_id, :amount)
    end

    def get_balance_params
      params.require(:bank_accounts).permit(:label , :balance)
    end

    def find_account_params
      result = {
        :username => params[:username],
        :label => params[:amount][:label]
      }
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<div class = "tansfer_center">
<%= form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :from_account_id %><br>
  <%= f.select(:from_account_id, options_for_select(@bank_account_options)) %>
  </div>

  <div class="field">
    <%= f.label :to_account_id %><br>
    <%= f.text_field :to_account_id %>
  </div>
  
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount, step: "any"%>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

<style>
  .actions{
    margin-top: 10px;
    color: #000000;
  }
  field{
    margin-right: 20px;
  }
  .transfer_center{
    text-align: center;
    background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrC3aWdLlOxO6Y3VKXO0g_iJK7Q_NkzTU9l3TikD_UIm65iv1wGA");
  }
</style>

app/views/transfers/find.html.erb
<h1>THis is transfer!!!!<h1>

app/views/transfers/index.html.erb
<div class="list-center">
<h1>Listing transfers history</h1>
<table>
  <thead>
    <tr>
      <th> From account </th>
      <th> To account </th>
      <th> Amount </th>
      <th> Time </th>
      <th colspan="3"></th>
    </tr>

  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <!-- need to change to label  -->
        <td><%= transfer.from_account_id %></td>
        <td><%= transfer.to_account_id %></td>
        <td><%= transfer.amount %></td>
        <td><%= Time.now.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Make A Transfer', new_transfer_path %>
</div>



<style>
   
    .list-center{
      text-align: center;
      background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrC3aWdLlOxO6Y3VKXO0g_iJK7Q_NkzTU9l3TikD_UIm65iv1wGA");
      color: #000000;
    }
</style>

app/views/transfers/new.html.erb
<div class="tran-center">
<h1>Transferin..</h1>

<%= render 'form' %>

<div class = "button_showh">
<%= link_to 'show history', transfers_path %>
</div>

<style>
	.tran-center{
		background-image: url("https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRRv8Z3XHY3NZl9Z_w-4mD0vIUt7DhojCLxTFZAVyRiSvwPYHF7");
		text-align: center;
	}
	.button_showh{
		color: #000000;
	}
</style>

app/views/transfers/show.html.erb
<div class = "tr-center">
<p id="notice"><%= notice %></p>
<p>
  <strong>From account:</strong>
  <%= @transfer.From_Account %>
</p>

<p>
  <strong>To account:</strong>
  <%= @transfer.To_Account %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transfer.Amount %>
</p>

<p>
	<strong>Time:</strong>
	<%= Time.strftime("%d/%m/%Y %H:%M") %>
</p>

<%= link_to 'Back', transfers_path %>
</div>

<style>
	.tr-center{
		text-align: center;
		background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrC3aWdLlOxO6Y3VKXO0g_iJK7Q_NkzTU9l3TikD_UIm65iv1wGA");
		text-align: ceter;
	}
	p{
		text-align: center;
	}

</style>